services:
  - type: web
    name: vertical-ring-ui
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 10000
    nodeVersion: 18.19.1
